
lizi: true

CON_PORT: RiCBoard
FILE_NAME: lizi_hatal_v2
Battery/name: battery_monitor
Battery/pubHz: 10
Battery/voltageDividerRatio: 6
URF0/publishHz: 20
URF0/name: right_urf
URF0/frameId: Right_URF_link
URF0/type: 10
URF0/port: 1
URF1/publishHz: 20
URF1/name: rear_urf
URF1/frameId: Rear_URF_link
URF1/type: 10
URF1/port: 2
URF2/publishHz: 20
URF2/name: left_urf
URF2/frameId: Left_URF_link
URF2/type: 10
URF2/port: 3
IMU/publishHz: 20
IMU/name: imu
IMU/frameId: RiC_Frame
IMU/camp: 0
IMU/orientation: 0
IMU/fusionHz: 50
IMU/fuseGyro: 0
closeLoop0/publishHz: 50
closeLoop0/name: front_left_motor
closeLoop0/LPFAlpha: 0.7
closeLoop0/LPFHz: 50
closeLoop0/driverAddress: 999
closeLoop0/channel: 4
closeLoop0/port: 2
closeLoop0/PIDHz: 1000
closeLoop0/kP: 50.0
closeLoop0/kI: 55.0
closeLoop0/kD: 0
closeLoop0/limit: 1.0
closeLoop0/maxSpeed: 16.0
closeLoop0/cpr: 4480
closeLoop0/timeout: 1000
closeLoop0/motorType: 1
closeLoop0/encoderType: 1
closeLoop0/direction: 1
closeLoop0/directionE: -1
closeLoop1/publishHz: 50
closeLoop1/name: front_right_motor
closeLoop1/LPFAlpha: 0.7
closeLoop1/LPFHz: 50
closeLoop1/driverAddress: 999
closeLoop1/channel: 3
closeLoop1/port: 1
closeLoop1/PIDHz: 1000
closeLoop1/kP: 50.0
closeLoop1/kI: 55.0
closeLoop1/kD: 0
closeLoop1/limit: 1.0
closeLoop1/maxSpeed: 16.0
closeLoop1/cpr: 4480
closeLoop1/timeout: 1000
closeLoop1/motorType: 1
closeLoop1/encoderType: 1
closeLoop1/direction: -1
closeLoop1/directionE: 1
closeLoop2/publishHz: 50
closeLoop2/name: rear_left_motor
closeLoop2/LPFAlpha: 0.7
closeLoop2/LPFHz: 50
closeLoop2/driverAddress: 999
closeLoop2/channel: 0
closeLoop2/port: 3
closeLoop2/PIDHz: 1000
closeLoop2/kP: 50.0
closeLoop2/kI: 55.0
closeLoop2/kD: 0
closeLoop2/limit: 1.0
closeLoop2/maxSpeed: 16.0
closeLoop2/cpr: 4480
closeLoop2/timeout: 1000
closeLoop2/motorType: 1
closeLoop2/encoderType: 1
closeLoop2/direction: 1
closeLoop2/directionE: -1
closeLoop3/publishHz: 50
closeLoop3/name: rear_right_motor
closeLoop3/LPFAlpha: 0.7
closeLoop3/LPFHz: 50
closeLoop3/driverAddress: 999
closeLoop3/channel: 1
closeLoop3/port: 4
closeLoop3/PIDHz: 1000
closeLoop3/kP: 50.0
closeLoop3/kI: 55.0
closeLoop3/kD: 0
closeLoop3/limit: 1.0
closeLoop3/maxSpeed: 16.0
closeLoop3/cpr: 4480
closeLoop3/timeout: 1000
closeLoop3/motorType: 1
closeLoop3/encoderType: 1
closeLoop3/direction: -1
closeLoop3/directionE: 1
#~ Diff/publishHz: 50
#~ Diff/name: diff_driver
#~ Diff/rWheel: 0.065
#~ Diff/width: 0.255
#~ Diff/baseLink: base_link
#~ Diff/odom: odom_link
#~ Diff/slip: 0.5
#~ Diff/maxAng: 16.0
#~ Diff/maxLin: 16.0
#~ Diff/motorFL: 0
#~ Diff/motorFR: 1
#~ Diff/motorBL: 2
#~ Diff/motorBR: 3
IMU_INIT: 1
GPS_INIT: 0
PPM_INIT: 0
BAT_INIT: 1
DIFF_INIT: 0
DIFF_INIT_OP: 0
DIFF_CLOSE_FOUR: 0
closeLoopNum: 4
switchNum: 0
servoNum: 0
relayNum: 0
URFNum: 3
openLoopNum: 0
emergencySwitchNum: 0


left_motor_pub: 'front_left_motor/command'
left_motor_sub: 'front_left_motor/feedback'
right_motor_pub: 'front_right_motor/command'
right_motor_sub: 'front_right_motor/feedback'
left_motor_joint_name: 'fl_wheel_joint'
right_motor_joint_name: 'fr_wheel_joint'

rear_left_motor_pub: 'rear_left_motor/command'
rear_left_motor_sub: 'rear_left_motor/feedback'
rear_right_motor_pub: 'rear_right_motor/command'
rear_right_motor_sub: 'rear_right_motor/feedback'
rear_left_motor_joint_name: 'rl_wheel_joint'
rear_right_motor_joint_name: 'rr_wheel_joint'



