controller_list:
    - name: arm_trajectory_controller
      default: true
      type: FollowJointTrajectory
      action_ns: follow_joint_trajectory
      joints:
        - base_rotation_joint
        - shoulder_joint
        - elbow1_joint
        - elbow2_joint
        - wrist_joint

    - name: gripper_controller
      default: false
      type: GripperCommand
      action_ns: gripper_cmd
      joints:
        - left_finger_joint
        - right_finger_joint

    # - name: gripper_jta_controller
    #   default: true
    #   type: FollowJointTrajectory
    #   action_ns: follow_joint_trajectory
    #   joints:
    #     - left_finger_joint
    #     - right_finger_joint
