joint_names_list: ['arm_rotation1_joint', 'arm_rotation2_joint', 'arm_shoulder1_joint', 'arm_shoulder2_joint', 'arm_shoulder3_joint', 'arm_wrist_joint']

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20  

joint_position_controller:
    type: position_controllers/JointGroupPositionController
    joints: ['arm_rotation1_joint', 'arm_rotation2_joint', 'arm_shoulder1_joint', 'arm_shoulder2_joint', 'arm_shoulder3_joint', 'arm_wrist_joint']
    publish_rate: 20
