servos: [{id: 1,joint_name: rotation1_joint, protocol_version: 2.0, torque: 1}, {id: 2,joint_name: shoulder1_joint, protocol_version: 2.0, torque: 1}, {id: 3,joint_name: shoulder2_joint, protocol_version: 2.0, torque: 1}, {id: 4,joint_name: rotation2_joint, protocol_version: 2.0, torque: 1}, {id: 5,joint_name: shoulder3_joint, protocol_version: 2.0, torque: 1}, {id: 6,joint_name: wrist_joint, protocol_version: 2.0, torque: 1}, {id: 7,joint_name: left_finger_joint, protocol_version: 1.0, torque: 0}, {id: 8,joint_name: right_finger_joint, protocol_version: 1.0, torque: 0}]

device: "/dev/ttyS0"
serial_timeout_ms: 1000000000
device_baudrate: 57600
init_speed_protocol1: 1.0
init_speed_protocol2: 0.3

arm_joints: [rotation1_joint, shoulder1_joint, shoulder2_joint, rotation2_joint,  shoulder3_joint, wrist_joint]
gripper_joints: [left_finger_joint, right_finger_joint]

