base_link: 'base_link'

# =====================================================
eef:
  end_effector_name: 'eef'

  #default grasp params
  joints : ['left_finger_joint', 'right_finger_joint']
  pregrasp_posture : [-0.57, 0.57]
  pregrasp_time_from_start : 5.0
  grasp_posture : [0.3, -0.3]
  grasp_time_from_start : 5.0

  #desired pose from end effector to grasp
  grasp_pose_to_eef : [0.054, 0.0, 0.018]

  #desired pose from end effector to grasp - [r, p, y]
  grasp_pose_to_eef_rotation : [0, 1.5708, 0] # 1.5707 = PI/2

  end_effector_parent_link: 'wrist_link'

