teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: joy_vel
    deadman_buttons: [6]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 0
        target: angular.z
        scale: 1.0
  




