CON_PORT: RiCBoard
FILE_NAME: test_imu
IMU/publishHz: 20
IMU/name: imu
IMU/frameId: RiC_Frame
IMU/camp: 0
IMU/orientation: 0
IMU/fusionHz: 50
IMU/fuseGyro: 0
IMU_INIT: 1
GPS_INIT: 0
PPM_INIT: 0
BAT_INIT: 0
DIFF_INIT: 0
DIFF_INIT_OP: 0
DIFF_CLOSE_FOUR: 0
closeLoopNum: 0
switchNum: 0
servoNum: 0
relayNum: 0
URFNum: 0
openLoopNum: 0
emergencySwitchNum: 0
