controller_list:
    - name: dynamixel_pro_action_server
      default: true
      type: FollowJointTrajectory
      action_ns: follow_joint_trajectory
      joints: 
        - rotation1_joint
        - shoulder1_joint
        - shoulder2_joint
        - rotation2_joint
        - shoulder3_joint
        - wrist_joint

    #- name: gripper_server
      #default: true
      #type: GripperCommand

      #joints: 
        #- gripper_l_joint
        #- gripper_r_joint
