
robot_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

arm_position_controller:
    type: position_controllers/JointGroupPositionController
    joints: ['rotation1_joint', 'shoulder1_joint', 'shoulder2_joint', 'rotation2_joint', 'shoulder3_joint', 'wrist_joint']
    publish_rate: 20

arm_trajectory_controller:
  type: position_velocity_controllers/JointTrajectoryController
  joints:
     - rotation1_joint
     - shoulder1_joint 
     - shoulder2_joint 
     - rotation2_joint 
     - shoulder3_joint 
     - wrist_joint 
  constraints:
    goal_time: 0.5                   # Override default
    stopped_velocity_tolerance: 0.5 # Override default
    rotation1_joint: {trajectory: 0.2, goal: 0.2}
    shoulder1_joint: {trajectory: 0.2, goal: 0.2}
    shoulder2_joint: {trajectory: 0.2, goal: 0.2}
    rotation2_joint: {trajectory: 0.2, goal: 0.2}
    shoulder3_joint: {trajectory: 0.2, goal: 0.2}
    wrist_joint: {trajectory: 0.2, goal: 0.2}


gripper_controller:
 type: position_controllers/GripperActionControllerTwo
 leftJoint: 'left_finger_joint'
 rightJoint: 'right_finger_joint'
 goal_tolerance: 0.01
 stalled_velocity_threshold: 0.005
 stall_timeout: 5.0

