
left_finger_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_finger_joint
    joint_speed: 0.2
    max_torque: 0.1
    motor:
        id: 1
        init: 2048
        min: 1480
        max: 2622

right_finger_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_finger_joint
    joint_speed: 0.2
    max_torque: 0.1
    motor:
        id: 2
        init: 2048
        min: 1480
        max: 2622

left_finger_topic_pub: 'left_finger_controller/command'
left_finger_topic_sub: 'left_finger_controller/state'
left_finger_joint: 'left_finger_joint'

right_finger_topic_pub: 'right_finger_controller/command'
right_finger_topic_sub: 'right_finger_controller/state'
right_finger_joint: 'right_finger_joint'
