servos: [{id: 1,joint_name: rotation1_joint, protocol_version: 2.0}, {id: 2,joint_name: shoulder1_joint, protocol_version: 2.0}, {id: 3,joint_name: shoulder2_joint, protocol_version: 2.0}, {id: 4,joint_name: rotation2_joint, protocol_version: 2.0}, {id: 5,joint_name: shoulder3_joint, protocol_version: 2.0}, {id: 6,joint_name: wrist_joint, protocol_version: 2.0}, {id: 7,joint_name: left_finger_joint, protocol_version: 1.0}, {id: 8,joint_name: right_finger_joint, protocol_version: 1.0}]

device: "/dev/ttyUSB0"
serial_timeout_ms: 1000000000
baudrates_t: 57142


