arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - base_rotation_joint 
     - shoulder_joint 
     - elbow1_joint 
     - elbow2_joint 
     - wrist_joint 
  constraints:
    goal_time: 10.5                   # Override default
    stopped_velocity_tolerance: 10.5 # Override default
    base_rotation_joint: {trajectory: 0.9, goal: 0.2}
    shoulder_joint: {trajectory: 0.9, goal: 0.2}
    elbow1_joint: {trajectory: 0.9, goal: 0.2}
    elbow2_joint: {trajectory: 0.9, goal: 0.2}
    wrist_joint: {trajectory: 0.9, goal: 0.2}
