#joint_position_controller:
 #   type: position_controllers/JointGroupPositionController
 #   joints: ['arm_rotation1_joint', 'arm_rotation2_joint', 'arm_shoulder1_joint', 'arm_shoulder2_joint', 'arm_shoulder3_joint', 'arm_wrist_joint','gripper_l_joint','gripper_r_joint']
#    publish_rate: 20
joint_position_controller:
    type: position_controllers/JointGroupPositionController
    joints: ['rotation1_joint', 'shoulder1_joint']
    publish_rate: 20


#arm_shoulder1_joint_controller:
 # type: position_controllers/JointPositionController
 # joint: arm_shoulder1_joint
 # pid: { p: 13.43, i: 0.0, d: 24.42, i_clamp: 1 }
#arm_rotation2_joint_controller:
  #type: effort_controllers/JointPositionController
  #joint: arm_rotation2_joint
  #pid: { p: 13.43, i: 0.0, d: 24.42, i_clamp: 1 }
#arm_shoulder1_joint_controller:
  #type: effort_controllers/JointPositionController
  #joint: arm_shoulder1_joint
  #pid: { p: 13.43, i: 0.0, d: 24.42, i_clamp: 1 }
#arm_shoulder2_joint_controller:
  #type: effort_controllers/JointPositionController
  #joint: arm_shoulder2_joint
  #pid: { p: 13.43, i: 0.0, d: 24.42, i_clamp: 1 }
#arm_shoulder3_joint_controller:
  #type: effort_controllers/JointPositionController
  #joint: arm_shoulder3_joint
  #pid: { p: 13.43, i: 0.0, d: 24.42, i_clamp: 1 }
#arm_wrist_joint_controller:
  #type: effort_controllers/JointPositionController
  #joint: arm_wrist_joint
  #pid: { p: 13.43, i: 0.0, d: 24.42, i_clamp: 1 }
#gripper_l_joint_controller:
  #type: effort_controllers/JointPositionController
  #joint: gripper_l_joint
  #pid: { p: 13.43, i: 0.0, d: 24.42, i_clamp: 1 }
#gripper_r_joint_controller:
  #type: effort_controllers/JointPositionController
  #joint: gripper_r_joint
  #pid: { p: 13.43, i: 0.0, d: 24.42, i_clamp: 1 }
#arm_r_shoulder_roll_upper_controller:
 # type: effort_controllers/JointPositionController
 #joint: arm_r_shoulder_roll_upper_joint
 # pid: { p: 13.43, i: 0.0, d: 24.42, i_clamp: 1 }
 
   #gains:
      #arm_rotation1_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      #arm_rotation2_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      #arm_shoulder1_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      #arm_shoulder2_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      #arm_shoulder3_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      #arm_wrist_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      #gripper_l_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      #gripper_r_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0} 
      
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - rotation1_joint
     - shoulder1_joint 
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      rotation1_joint: {trajectory: 0.1, goal: 0.1}
      shoulder1_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  
arm_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
