servos: [{id: 1,joint_name: arm_rotation1_joint}, {id: 2,joint_name: arm_shoulder1_joint}, {id: 3,joint_name: arm_shoulder2_joint}, {id: 4,joint_name: arm_rotation2_joint}, {id: 5,joint_name: arm_shoulder3_joint}, {id: 6,joint_name: arm_wrist_joint}]
#servos: [{id: 2,joint_name: arm_wrist_joint}]
device: "/dev/USB2DYNAMIXEL_ARM"
serial_timeout_ms: 1000000000
